actually making this script more friendly

diff --git a/compile-script b/compile-script
--- a/compile-script
+++ b/compile-script
@@ -1,7 +1,9 @@
 #!/bin/sh
 pldir=$(pwd)
-rootdir=$(pwd)/build
-output=$(pwd)/output
+rootdir=$pldir/build
+output=$pldir/output
+output_rootfs=$output/rootfs
+output_initramfs=$output/initramfs
 
 if [ "$toolchain_prefix" = "" ]; then
 	toolchain_prefix=$(echo ~/cross)
@@ -17,8 +19,12 @@ fi
 
 export PATH="$toolchain_prefix/bin:$PATH"
 
-# init
-if [ ! -d $rootdir ]; then
+
+init_script(){
+	if [ -d $rootdir ]; then
+		rm -rf build
+	fi
+
 	if [ ! -d tarballs ]; then
 		./get-deps $@
 	fi
@@ -34,7 +40,7 @@ if [ ! -d $rootdir ]; then
 	sed -i 's/limits.h/linux\/limits.h/g' $rootdir/gcc-10.3.0/libsanitizer/asan/asan_linux.cpp
 	sed -i '20 i #include <bits/xopen_lim.h>' $rootdir/busybox-1.34.1/include/libbb.h
 	cd $rootdir
-fi
+}
 
 clean_rootdir(){
 	for i in $(ls $rootdir); do
@@ -138,21 +144,25 @@ compile_toolchain(){
 	fi
 }
 
+compile_initramfs(){
+	
+		echo "CONFIG_STATIC=y" >> .config
+}
+
 compile_rootfs(){
 	if ! command -v $arch-pocket-linux-gnu-gcc &> /dev/null; then
-		compile_toolchain
-		clean_rootdir
+		echo "Error: toolchain for $arch not found in PATH"
+		exit 1
 	fi
 
 	for i in bin dev sys proc lib sbin usr/bin usr/lib usr/sbin etc root mnt home tmp; do
 		mkdir -p $output/$i
 	done
 
-	if [ ! -r $output/bin/busybox ]; then
+	if [ ! -r $output/rootfs/bin/busybox ]; then
 		cd $rootdir/busybox-1.34.1
 
 		make defconfig
-		echo "CONFIG_STATIC=y" >> .config
 		echo "CONFIG_CROSS_COMPILER_PREFIX=$toolchain_prefix/bin/$arch-pocket-linux-gnu-" >> .config
 
 		make -j$threads
@@ -234,5 +244,39 @@ compile_rootfs(){
 	fi
 }
 
-clean_rootdir
-compile_rootfs
+compile_kernel(){
+
+}
+
+script(){
+	case $1 in
+		init)
+			init_script $2
+
+		build)
+			if [ ! -d $rootdir ]; then
+				init_script $4
+			fi
+
+			case $3 in
+				toolchain)
+					compile_toolchain
+					;;
+
+				rootfs)
+					compile_rootfs
+					;;
+
+				kernel)
+					compile_kernel
+					;;;
+			esac
+
+		clean)
+			rm -rf build output
+			;;
+
+		clean-all)
+			rm -rf build output tarballs
+	esac
+}
