almost completed :3

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -11,7 +11,7 @@ toolchain_prefix="$(echo ~/cross)"
 threads=$(nproc)
 
 compile_target="i486-pocket-linux-gnu"
-linux_arch="x86"
+linux_arch="i386"
 arch="i486"
 abi=""
 dist="gnu"
@@ -19,8 +19,12 @@ dist="gnu"
 start_time=""
 end_time=""
 
+if [ $(echo $PATH | grep -c "$toolchain_prefix") -eq 0 ]; then
+	export PATH="$toolchain_prefix/bin:$PATH"
+fi
+
 _get_deps(){
-	local URL="http://kernel.org/pub/linux/kernel/v5.x/linux-5.16.10.tar.xz http://busybox.net/downloads/busybox-1.34.1.tar.bz2"
+	local URL="http://kernel.org/pub/linux/kernel/v5.x/linux-5.19.8.tar.xz http://busybox.net/downloads/busybox-1.34.1.tar.bz2"
 	local PKG="binutils/binutils-2.37.tar.gz bison/bison-3.7.6.tar.gz gcc/gcc-10.3.0/gcc-10.3.0.tar.gz gmp/gmp-6.2.1.tar.xz make/make-4.3.tar.gz mpc/mpc-1.2.1.tar.gz mpfr/mpfr-4.1.0.tar.gz"
 
 	if [ "$dist" = "musl" ]; then
@@ -261,6 +265,9 @@ compile_rootfs(){
 	if [ ! -r "$toolchain_prefix/bin/$compile_target-gcc" ]; then
 		echo "Error: You do not have the compiler for system $compile_target installed. Please run $0 --build toolchain and try again"
 		exit 1
+	elif [ $(id -u) -ne 0 ]; then
+		echo "Error: You are not root"
+		exit 3
 	fi
 
 	printf "Creating rootfs structure..."
@@ -273,13 +280,11 @@ compile_rootfs(){
 
 	if [ ! -r "$output_rootfs/usr/lib/libc.a" ]; then
 		local common_flags="--prefix=/usr --with-sysroot=/ --disable-multilib --host=$compile_target --datarootdir=/opt/share --includedir=/opt/include"
-		local make_flags="DESTDIR=$output_rootfs install"
 		if [ "$dist" = "musl" ]; then
 			cd "$build/musl-1.2.3"
 			printf "Configuring musl..."
 			script -qeac "./configure $common_flags 2>&1" "$logfile" >/dev/null
 			printf "Done.\nCompiling musl..."
-			make_flags="$make_flags-strip"
 		else
 			cd "$build/glibc-2.31"
 			mkdir -p build
@@ -296,7 +301,7 @@ compile_rootfs(){
 
 		script -qeac "make -j$threads 2>&1" "$logfile" >/dev/null
 		printf "Done\nInstalling libc..."
-		script -qeac "make $make_flags 2>&1" "$logfile" >/dev/null
+		script -qeac "make DESTDIR=$output_rootfs install 2>&1" "$logfile" >/dev/null
 		echo "Done."
 		cd "$build"
 	fi
@@ -325,8 +330,6 @@ compile_rootfs(){
 		script -qeac "../configure --prefix=/usr --with-sysroot=/ --disable-multilib --disable-bootstrap --host=$compile_target --disable-libstdcxx-debug --enable-languages=c,c++ --with-build-sysroot=$output_rootfs --libexecdir=/opt/libexec --bindir=/opt/bin --includedir=/opt/include --with-gxx-include-dir=/opt/include/c++/10.3.0 --datarootdir=/opt/share --with-native-system-header-dir=/opt/include $extra_flag 2>&1" "$logfile" >/dev/null
 		printf "Done.\nCompiling GCC..."
 		script -qeac "make -j$threads 2>&1" >/dev/null
-		printf "Done.\nInstalling libgcc..."
-		script -qeac "make install-strip-target-libgcc DESTDIR=$output_rootfs 2>&1" "$logfile" >/dev/null
 		printf "Done.\nInstalling libstdc++..."
 		script -qeac "make install-strip-target-libstdc++-v3 DESTDIR=$output_rootfs 2>&1" "$logfile" >/dev/null
 		echo "Done."
@@ -362,9 +365,9 @@ compile_rootfs(){
 	mkdir -p "$output_rootfs/usr/include"
 	set +e
 	printf "Creating necessary device nodes..."
-	sudo mknod "$output_rootfs/dev/console" c 5 1 2>/dev/null
-	sudo mknod "$output_rootfs/dev/tty" c 5 0 2>/dev/null
-	sudo mknod "$output_rootfs/dev/null" c 1 3 2>/dev/null
+	mknod "$output_rootfs/dev/console" c 5 1 2>/dev/null
+	mknod "$output_rootfs/dev/tty" c 5 0 2>/dev/null
+	mknod "$output_rootfs/dev/null" c 1 3 2>/dev/null
 	echo "Done."
 }
 
@@ -402,6 +405,8 @@ compile_devrfs(){
 
 		printf "Installing GCC C/C++ Compilers..."
 		script -qeac "make install-strip DESTDIR=$output_rootfs 2>&1" >/dev/null
+		printf "Done.\nInstalling libgcc..."
+		script -qeac "make install-strip-target-libgcc DESTDIR=$output_rootfs 2>&1" "$logfile" >/dev/null
 		echo "Done"
 		cd ../..
 	fi
@@ -425,14 +430,14 @@ compile_kernel(){
 
 	if [ ! -f .config ]; then
 		if [ "$dist" = "musl" ]; then
-			make -s ARCH=$linux_arch allnoconfig
+			make -s ARCH=$linux_arch allnoconfig 2>1 >/dev/null
 		else
-			make -s ARCH=$linux_arch alldefconfig
+			make -s ARCH=$linux_arch alldefconfig 2>1 >/dev/null
 		fi
 	fi
 
-	CC=$compile_target-gcc make -j$threads bzImage
-	cp arch/$linux_arch/boot/bzImage $output
+	script -qeac "CC=$compile_target-gcc make -j$threads bzImage" "$logfile"
+	cp arch/$linux_arch/boot/bzImage "$output"
 }
 
 create_boot_image(){
@@ -507,7 +512,11 @@ while [ $# -gt 0 ]; do
 			fi
 
 			if [ $(echo $arch | grep -c 86) -ne 0 ]; then
-				linux_arch="x86"
+				if [ $(echo $arch | grep -c i) -ne 0 ]; then
+					linux_arch="i386"
+				else
+					linux_arch="x86"
+				fi
 			elif [ "$arch" = "aarch64" ]; then
 				linux_arch="arm64"
 			else
@@ -516,6 +525,14 @@ while [ $# -gt 0 ]; do
 
 			compile_target="$arch-pocket-linux-$dist$abi"
 			shift
+			;;
+		"--toolchain-prefix")
+			toolchain_prefix="$2"
+			shift
+			;;
+		"--test-toolchain")
+			$compile_target-gcc --version
+			exit 0
 			;;
 		"--clean")
 			_runtime_calc start
@@ -551,11 +568,12 @@ while [ $# -gt 0 ]; do
 		"--help")
 			printf "Usage: $0 {--target-arch|--threads} [--init|--clean|--hard-clean|--build] [value]\n\n"
 			echo "--init				Initializes the build system by downloading necessary components and unpacking them"
-			echo "--target-system [arch-dist]	Specifies the CPU architecture and the C library to be used. The default target is i486-gnu"
+			echo "--target-system [arch-dist]	Specifies the CPU architecture and the C library to be used. Default: i486-gnu"
+			echo "--toolchain-prefix [path]		Sets the target system's toolchain's install directory. Default: ~/cross"
 			echo "--clean				Cleans the build directory"
 			echo "--hard-clean			Removes any directories created by --init"
 			echo "--threads [n]			Sets the amount of threads to be used in compilation"
-			echo "--build [action]		Compiles toolchain, rootfs, devrfs or kernel. The previous list of words are the supported operations."
+			echo "--build [action]		Compiles toolchain, rootfs, devrfs, kernel or boot-img. The previous list of words are the supported operations."
 			exit 0
 			;;
 		*)
@@ -570,5 +588,24 @@ echo "Log file: $logfile"
 echo "Target System: $compile_target"
 printf "Toolchain install directory: $toolchain_prefix\n\n"
 _runtime_calc start
-compile_$action
+case $action in
+	toolchain)
+		compile_toolchain
+		;;
+	rootfs)
+		compile_rootfs
+		;;
+	devrfs)
+		compile_devrfs
+		;;
+	kernel)
+		compile_kernel
+		;;
+	boot-img)
+		create_boot_image
+		;;
+	*)
+		printf "Error: Unknown build command. Run $0 --help for a list of supported commands."
+		exit 4
+esac
 _runtime_calc stop
